api:
	air --build.cmd "go build -o bin/api cmd/api/main.go" --build.bin "./bin/api"

discord:
	air --build.cmd "go build -o bin/discord cmd/discord/main.go" --build.bin "./bin/discord"

.PHONY: api discord
